ekf_filter_node:
  ros__parameters:
    frequency: 30.0
    sensor_timeout: 0.1
    two_d_mode: false

    # IMU - use orientation and angular velocity
    imu0: /imu/data
    imu0_config: [false, false, false,    # position (x, y, z) - not used
                  true,  true,  true,     # orientation (roll, pitch, yaw)
                  false, false, false,    # linear velocity (x, y, z) - not used
                  true,  true,  true,     # angular velocity (x, y, z)
                  false, false, false,    # linear acceleration (x, y, z) - not used
                  false, false, false]    # angular acceleration (x, y, z) - not used
    imu0_differential: false
    imu0_relative: false
    imu0_remove_gravitational_acceleration: true

    # Visual odometry from rtabmap (position and velocity)
    odometry0: /odom
    odometry0_config: [true,  true,  true,    # position (x, y, z)
                      false, false, false,    # orientation (roll, pitch, yaw) - not used
                      true,  true,  true,     # linear velocity (x, y, z)
                      false, false, false,    # angular velocity (x, y, z) - not used
                      false, false, false,    # linear acceleration (x, y, z) - not used
                      false, false, false]    # angular acceleration (x, y, z) - not used

    map_frame: map
    odom_frame: odom
    base_link_frame: base_link
    world_frame: odom

    publish_tf: true
    publish_acceleration: false